"""Tests for loudness measurement and normalization in processing/audio.py.

Most tests run real ffmpeg on tones generated by the ``make_tone`` fixture;
the retry logic is tested with ffmpeg calls stubbed out.
"""

import logging
import subprocess
import threading
import time
from collections.abc import Callable
from pathlib import Path

import mutagen
import pytest

from kidsplay_models.media import MediaType
from kidsplay_server.processing import audio
from kidsplay_server.processing.audio import (
    LoudnessConfig,
    LoudnessError,
    LoudnessMeasurement,
    LoudnessTarget,
    NormalizationResult,
    UnmeasurableLoudnessError,
    ffmpeg_available,
    measure_loudness,
    measure_true_peak,
    normalize_loudness,
)
from kidsplay_server.processing.resources import JobCancelledError

MakeTone = Callable[..., Path]  # the ``make_tone`` fixture from conftest.py

TARGET = LoudnessTarget(integrated_lufs=-16.0, true_peak_dbtp=-1.5)


# ---------------------------------------------------------------------------
# Config and targets
# ---------------------------------------------------------------------------


class TestLoudnessConfig:
    def test_defaults(self) -> None:
        cfg = LoudnessConfig()
        assert cfg.enabled
        assert cfg.target_for(MediaType.MUSIC) == TARGET
        # Audiobooks get the same target unless configured otherwise.
        assert cfg.target_for(MediaType.AUDIOBOOK) == TARGET

    def test_per_type_targets(self) -> None:
        cfg = LoudnessConfig(
            target_lufs=-18.0,
            true_peak_dbtp=-2.0,
            music_target_lufs=-14.0,
            audiobook_target_lufs=-12.0,
        )
        assert cfg.target_for(MediaType.MUSIC) == LoudnessTarget(-14.0, -2.0)
        assert cfg.target_for(MediaType.AUDIOBOOK) == LoudnessTarget(-12.0, -2.0)
        assert cfg.target_for(MediaType.PHOTO) == LoudnessTarget(-18.0, -2.0)

    def test_unset_type_target_falls_back(self) -> None:
        cfg = LoudnessConfig(target_lufs=-20.0, audiobook_target_lufs=-14.0)
        assert cfg.target_for(MediaType.MUSIC).integrated_lufs == -20.0

    @pytest.mark.parametrize(
        "make",
        [
            lambda: LoudnessConfig(target_lufs=-4.0),
            lambda: LoudnessConfig(target_lufs=-71.0),
            lambda: LoudnessConfig(music_target_lufs=0.0),
            lambda: LoudnessConfig(audiobook_target_lufs=-80.0),
            lambda: LoudnessConfig(true_peak_dbtp=0.5),
            lambda: LoudnessConfig(true_peak_dbtp=-10.0),
        ],
    )
    def test_out_of_range_rejected(self, make: Callable[[], LoudnessConfig]) -> None:
        with pytest.raises(ValueError, match="must be between"):
            make()


class TestLoudnessTargetMatches:
    def test_equal(self) -> None:
        assert TARGET.matches(-16.0, -1.5)

    def test_within_rounding(self) -> None:
        assert TARGET.matches(-16.004, -1.499)

    @pytest.mark.parametrize(
        ("lufs", "peak"), [(None, -1.5), (-16.0, None), (-14.0, -1.5), (-16.0, -1.0)]
    )
    def test_different_or_missing(self, lufs: float | None, peak: float | None) -> None:
        assert not TARGET.matches(lufs, peak)


def test_gain_db_is_output_minus_source() -> None:
    def m(i: float) -> LoudnessMeasurement:
        return LoudnessMeasurement(i, -3.0, 1.0, i - 10, 0.0)

    result = NormalizationResult(
        source=m(-28.0), output_lufs=-16.1, output_true_peak_dbtp=-5.0, mode="linear"
    )
    assert result.gain_db == pytest.approx(11.9)


# ---------------------------------------------------------------------------
# ffmpeg plumbing
# ---------------------------------------------------------------------------


def test_ffmpeg_available_follows_path(monkeypatch: pytest.MonkeyPatch) -> None:
    assert ffmpeg_available()  # CI and dev setups install ffmpeg
    monkeypatch.setenv("PATH", "")
    assert not ffmpeg_available()


def test_missing_ffmpeg_raises(
    monkeypatch: pytest.MonkeyPatch, make_tone: MakeTone
) -> None:
    tone = make_tone("tone.wav", -6)
    monkeypatch.setenv("PATH", "")
    with pytest.raises(LoudnessError, match="not installed"):
        measure_loudness(tone)


def test_undecodable_file_raises(tmp_path: Path) -> None:
    junk = tmp_path / "junk.mp3"
    junk.write_bytes(b"not audio at all" * 100)
    with pytest.raises(LoudnessError, match="ffmpeg exited"):
        measure_loudness(junk)


class TestParseReport:
    def test_takes_last_json_block(self) -> None:
        stderr = (
            'noise {"a": "1"}\n[Parsed_loudnorm_0 @ 0x1]\n{\n "input_i" : "-20.5"\n}'
        )
        assert audio._parse_loudnorm_report(stderr) == {"input_i": "-20.5"}

    def test_no_report(self) -> None:
        with pytest.raises(LoudnessError, match="no loudness report"):
            audio._parse_loudnorm_report("nothing here")

    def test_bad_json(self) -> None:
        with pytest.raises(LoudnessError, match="unreadable"):
            audio._parse_loudnorm_report("{ not json }")


class TestOutputSampleRate:
    @pytest.mark.parametrize(("rate", "expected"), [(22050, 22050), (48000, 48000)])
    def test_mp3_rates_kept(
        self, make_tone: MakeTone, rate: int, expected: int
    ) -> None:
        tone = make_tone(f"t{rate}.wav", -6, seconds=1, sample_rate=rate)
        assert audio._output_sample_rate(tone) == expected

    def test_high_rate_becomes_48k(self, make_tone: MakeTone) -> None:
        tone = make_tone("t96.wav", -6, seconds=1, sample_rate=96000)
        assert audio._output_sample_rate(tone) == 48000

    def test_unreadable_defaults_to_44k1(self, tmp_path: Path) -> None:
        junk = tmp_path / "junk.bin"
        junk.write_bytes(b"\0" * 10)
        assert audio._output_sample_rate(junk) == 44100

    @pytest.mark.parametrize("suffix", [".opus", ".ogg"])
    def test_opus_rate_comes_from_ffprobe(
        self, make_tone: MakeTone, tmp_path: Path, suffix: str
    ) -> None:
        """mutagen reports no rate for Opus; it used to fall back to 44.1 kHz,
        resampling 48 kHz audio for nothing."""
        opus = _to_opus(make_tone("src.wav", -6, seconds=2), tmp_path / f"t{suffix}")
        info = mutagen.File(opus)
        assert getattr(getattr(info, "info", None), "sample_rate", None) is None
        assert audio._output_sample_rate(opus) == 48000

    def test_opus_source_is_normalized_at_48k(
        self, make_tone: MakeTone, tmp_path: Path
    ) -> None:
        opus = _to_opus(make_tone("src.wav", -18, seconds=3), tmp_path / "t.opus")
        out = tmp_path / "out.mp3"
        normalize_loudness(opus, out, TARGET)
        assert mutagen.File(out).info.sample_rate == 48000

    def test_without_ffprobe_falls_back_to_44k1(
        self, make_tone: MakeTone, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        opus = _to_opus(make_tone("src.wav", -6, seconds=1), tmp_path / "t.opus")
        monkeypatch.setenv("PATH", "")
        assert audio._probe_sample_rate(opus) is None
        assert audio._output_sample_rate(opus) == 44100

    def test_probe_of_a_non_audio_file_is_none(self, tmp_path: Path) -> None:
        junk = tmp_path / "junk.bin"
        junk.write_bytes(b"\0" * 10)
        assert audio._probe_sample_rate(junk) is None


# ---------------------------------------------------------------------------
# Measurement and normalization (real ffmpeg)
# ---------------------------------------------------------------------------


def test_measure_tones_12db_apart(make_tone: MakeTone) -> None:
    quiet = measure_loudness(make_tone("quiet.wav", -18))
    loud = measure_loudness(make_tone("loud.wav", -6))
    assert loud.integrated_lufs - quiet.integrated_lufs == pytest.approx(12, abs=0.2)
    assert loud.true_peak_dbtp > quiet.true_peak_dbtp


def test_silence_is_unmeasurable(tmp_path: Path) -> None:
    silent = tmp_path / "silent.wav"
    subprocess.run(
        [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-f",
            "lavfi",
            "-i",
            "anullsrc=r=44100:cl=mono",
            "-t",
            "3",
            str(silent),
        ],
        check=True,
    )
    with pytest.raises(UnmeasurableLoudnessError, match="too quiet"):
        measure_loudness(silent)


def test_two_tones_12db_apart_reach_the_target(
    make_tone: MakeTone, tmp_path: Path
) -> None:
    """Acceptance: both tones end within ±1 LU of the target, under the ceiling."""
    for name, volume in (("quiet", -18), ("loud", -6)):
        out = tmp_path / f"{name}-out.mp3"
        result = normalize_loudness(make_tone(f"{name}.wav", volume), out, TARGET)
        measured = measure_loudness(out)
        assert measured.integrated_lufs == pytest.approx(-16.0, abs=1.0), name
        assert measured.true_peak_dbtp <= TARGET.true_peak_dbtp, name
        # A steady tone fits under the ceiling, so a plain gain is used.
        assert result.mode == "linear", name
        # The reported output agrees with an independent measurement.
        assert result.output_lufs == pytest.approx(measured.integrated_lufs, abs=0.3)
        assert result.output_true_peak_dbtp == pytest.approx(
            measured.true_peak_dbtp, abs=0.05
        )


def test_custom_target(make_tone: MakeTone, tmp_path: Path) -> None:
    target = LoudnessTarget(integrated_lufs=-23.0, true_peak_dbtp=-2.0)
    out = tmp_path / "out.mp3"
    normalize_loudness(make_tone("t.wav", -6), out, target)
    assert measure_loudness(out).integrated_lufs == pytest.approx(-23.0, abs=1.0)


@pytest.mark.parametrize("ceiling", [-1.5, -3.0, -6.0])
def test_true_peak_never_exceeds_ceiling(
    make_tone: MakeTone, tmp_path: Path, ceiling: float
) -> None:
    """A full-scale burst on a quiet bed needs limiting, not just gain."""
    source = make_tone("spiky.wav", 0, spike=True)
    assert measure_loudness(source).true_peak_dbtp > 0
    out = tmp_path / "out.mp3"
    target = LoudnessTarget(integrated_lufs=-16.0, true_peak_dbtp=ceiling)
    result = normalize_loudness(source, out, target)
    assert result.mode == "dynamic"
    assert measure_loudness(out).true_peak_dbtp <= ceiling


def _quiet_with_peaks(tmp_path: Path) -> Path:
    """A quiet bed (-30 dB) with a short burst 12 dB below full scale.

    A plain gain to -16 LUFS would put the burst far over the ceiling, but the
    burst itself leaves ~10 dB of headroom, so it is "quiet, dynamic material"
    such as a lullaby: loudnorm limits it, or the gain can be capped.
    """
    path = tmp_path / "lullaby.wav"
    burst = (
        "sine=frequency=3000:sample_rate=44100:duration=5,"
        "volume=enable='between(t,1,1.05)':volume=2,"
        "volume=enable='not(between(t,1,1.05))':volume=0"
    )
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-nostdin", "-loglevel", "error", "-y"]
        + ["-f", "lavfi", "-i", "sine=frequency=440:sample_rate=44100:duration=5"]
        + ["-f", "lavfi", "-i", burst]
        + [
            "-filter_complex",
            "[0]volume=-30dB[a];[1]volume=-18dB[b];[a][b]amix=inputs=2:normalize=0",
            str(path),
        ],
        check=True,
    )
    return path


class TestNeverLimit:
    """``allow_limiting=False``: quiet material with loud peaks gets a smaller
    gain instead of a limiter, so it is never reshaped."""

    def test_the_fixture_needs_limiting_to_reach_the_target(
        self, tmp_path: Path
    ) -> None:
        measured = measure_loudness(_quiet_with_peaks(tmp_path))
        needed = TARGET.integrated_lufs - measured.integrated_lufs
        assert measured.true_peak_dbtp + needed > TARGET.true_peak_dbtp
        assert measured.true_peak_dbtp < TARGET.true_peak_dbtp - 3  # headroom exists

    def test_capped_gain_keeps_the_dynamics(self, tmp_path: Path) -> None:
        source = _quiet_with_peaks(tmp_path)
        out = tmp_path / "out.mp3"
        result = normalize_loudness(source, out, TARGET, allow_limiting=False)

        assert result.mode == "capped"
        before, after = measure_loudness(source), measure_loudness(out)
        assert after.true_peak_dbtp <= TARGET.true_peak_dbtp
        # Louder than the source, but short of the target: that is the price
        # of not limiting.
        assert result.gain_db > 3
        assert after.integrated_lufs < TARGET.integrated_lufs - 3
        # (loudnorm's own report and a fresh measurement differ by about a dB
        # on material this quiet and bursty, hence the tolerance.)
        assert result.gain_db == pytest.approx(
            after.integrated_lufs - before.integrated_lufs, abs=1.5
        )
        # Nothing but a constant gain was applied: the peak sits as far above
        # the loudness as it did in the source, where a limiter would have
        # pulled it down by several dB.
        assert after.true_peak_dbtp - after.integrated_lufs == pytest.approx(
            before.true_peak_dbtp - before.integrated_lufs, abs=1.5
        )

    def test_limiting_is_still_the_default(self, tmp_path: Path) -> None:
        out = tmp_path / "out.mp3"
        result = normalize_loudness(_quiet_with_peaks(tmp_path), out, TARGET)
        assert result.mode == "dynamic"
        assert measure_loudness(out).true_peak_dbtp <= TARGET.true_peak_dbtp

    def test_material_that_fits_is_normalized_as_usual(
        self, make_tone: MakeTone, tmp_path: Path
    ) -> None:
        out = tmp_path / "out.mp3"
        result = normalize_loudness(
            make_tone("t.wav", -18), out, TARGET, allow_limiting=False
        )
        assert result.mode == "linear"
        assert measure_loudness(out).integrated_lufs == pytest.approx(-16.0, abs=1.0)

    def test_cap_target_leaves_a_fitting_gain_alone(self) -> None:
        capped, was_capped = audio._cap_target(_measurement(-30.0, -20.0), TARGET)
        assert (capped, was_capped) == (TARGET, False)

    def test_cap_target_lowers_the_target_to_the_headroom(self) -> None:
        # Needs +20 dB but only 8.4 dB of headroom (with the safety margin).
        capped, was_capped = audio._cap_target(_measurement(-36.0, -10.0), TARGET)
        assert was_capped
        assert capped.integrated_lufs == pytest.approx(-36.0 + 8.4)
        assert capped.true_peak_dbtp == TARGET.true_peak_dbtp

    def test_cap_target_never_goes_below_the_measurable_floor(self) -> None:
        capped, was_capped = audio._cap_target(_measurement(-69.5, 3.0), TARGET)
        assert was_capped and capped.integrated_lufs >= audio.MIN_TARGET_LUFS


class TestCancel:
    def test_cancel_stops_the_running_ffmpeg(
        self, make_tone: MakeTone, tmp_path: Path
    ) -> None:
        long = make_tone("long.wav", -18, seconds=900)
        cancel = threading.Event()
        threading.Timer(0.5, cancel.set).start()
        started = time.monotonic()
        with pytest.raises(JobCancelledError):
            normalize_loudness(long, tmp_path / "out.mp3", TARGET, cancel=cancel)
        assert time.monotonic() - started < 5

    def test_an_already_set_event_runs_no_ffmpeg(
        self, make_tone: MakeTone, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        cancel = threading.Event()
        cancel.set()
        source = make_tone("t.wav", -18, seconds=1)

        def never(*args: object, **kwargs: object) -> None:
            raise AssertionError("ffmpeg must not start for a cancelled job")

        monkeypatch.setattr(subprocess, "Popen", never)
        with pytest.raises(JobCancelledError):
            normalize_loudness(source, tmp_path / "out.mp3", TARGET, cancel=cancel)


def test_output_is_mp3_at_source_rate(make_tone: MakeTone, tmp_path: Path) -> None:
    out = tmp_path / "out.mp3"
    normalize_loudness(make_tone("t.wav", -6, sample_rate=22050), out, TARGET)
    info = mutagen.File(out)
    assert info is not None
    assert info.mime[0] == "audio/mp3"
    assert info.info.sample_rate == 22050


def test_source_is_not_modified(make_tone: MakeTone, tmp_path: Path) -> None:
    source = make_tone("t.wav", -18)
    before = source.read_bytes()
    normalize_loudness(source, tmp_path / "out.mp3", TARGET)
    assert source.read_bytes() == before


def _to_opus(source: Path, dest: Path) -> Path:
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y", "-i", str(source)]
        + ["-c:a", "libopus", "-ar", "48000", str(dest)],
        check=True,
    )
    return dest


# ---------------------------------------------------------------------------
# Loud, clipped masters (real ffmpeg)
# ---------------------------------------------------------------------------


def test_clipped_master_converges_under_the_ceiling(
    clipped_master: Path, tmp_path: Path
) -> None:
    """Regression (#61): lowering loudnorm's ceiling by the overshoot did not
    converge for loud, clipped masters; the item failed after three attempts.
    A gain reduction after loudnorm does."""
    source = clipped_master
    measured = measure_loudness(source)
    assert measured.true_peak_dbtp > 5  # a clipped master

    out = tmp_path / "out.mp3"
    result = normalize_loudness(source, out, TARGET)

    after = measure_loudness(out)
    assert after.true_peak_dbtp <= TARGET.true_peak_dbtp
    assert result.output_true_peak_dbtp == pytest.approx(after.true_peak_dbtp, abs=0.05)
    # Ends a little under the target; loudnorm's own estimate of a limited
    # file's loudness is a few tenths of a dB optimistic.
    assert result.output_lufs < TARGET.integrated_lufs
    assert result.output_lufs == pytest.approx(after.integrated_lufs, abs=0.5)
    assert result.mode == "dynamic"
    # The gain reduction is recorded as a lower gain, not hidden.
    assert result.gain_db == pytest.approx(
        after.integrated_lufs - measured.integrated_lufs, abs=0.5
    )


def test_clipped_master_logs_the_peaks_at_info(
    clipped_master: Path, tmp_path: Path, caplog: pytest.LogCaptureFixture
) -> None:
    with caplog.at_level(logging.INFO, logger=audio.logger.name):
        normalize_loudness(clipped_master, tmp_path / "out.mp3", TARGET)
    (record,) = [r for r in caplog.records if r.levelno == logging.INFO]
    assert "dBTP over the -1.50 ceiling" in record.getMessage()
    assert "gain reduction" in record.getMessage()


# ---------------------------------------------------------------------------
# Peak retries (ffmpeg stubbed)
# ---------------------------------------------------------------------------


def _measurement(i: float, tp: float) -> LoudnessMeasurement:
    return LoudnessMeasurement(i, tp, 3.0, i - 10, 0.1)


class TestPeakRetries:
    @pytest.fixture
    def encodes(self, monkeypatch: pytest.MonkeyPatch) -> list[tuple[float, float]]:
        """Record the ``(ceiling, trim_db)`` each ``_encode`` call is given."""
        calls: list[tuple[float, float]] = []

        def fake_encode(
            source: Path,
            dest: Path,
            target: LoudnessTarget,
            measured: LoudnessMeasurement,
            sample_rate: int,
            cancel: threading.Event | None = None,
            trim_db: float = 0.0,
        ) -> tuple[str, float]:
            calls.append((target.true_peak_dbtp, trim_db))
            return "linear", -16.0 - trim_db

        def fake_measure(
            path: Path,
            target: LoudnessTarget | None = None,
            cancel: threading.Event | None = None,
        ) -> LoudnessMeasurement:
            return _measurement(-30.0, -20.0)

        monkeypatch.setattr(audio, "_encode", fake_encode)
        monkeypatch.setattr(audio, "measure_loudness", fake_measure)
        monkeypatch.setattr(
            audio, "_output_sample_rate", lambda path, cancel=None: 44100
        )
        return calls

    def _fake_peaks(self, monkeypatch: pytest.MonkeyPatch, peaks: list[float]) -> None:
        monkeypatch.setattr(
            audio, "measure_true_peak", lambda path, cancel=None: peaks.pop(0)
        )

    def test_overshoot_trims_the_gain_and_retries(
        self,
        monkeypatch: pytest.MonkeyPatch,
        encodes: list[tuple[float, float]],
        tmp_path: Path,
    ) -> None:
        self._fake_peaks(monkeypatch, [-1.2, -1.6])
        result = normalize_loudness(tmp_path / "in", tmp_path / "out", TARGET)
        # loudnorm's ceiling stays; the retry is trimmed by the 0.3 dB
        # overshoot plus a 0.1 dB margin.
        assert encodes[0] == (-1.5, 0.0)
        assert encodes[1] == (-1.5, pytest.approx(0.4))
        assert result.output_true_peak_dbtp == -1.6
        # The recorded loudness includes the trim.
        assert result.output_lufs == pytest.approx(-16.4)
        assert result.gain_db == pytest.approx(13.6)

    def test_trims_accumulate_with_a_growing_margin(
        self,
        monkeypatch: pytest.MonkeyPatch,
        encodes: list[tuple[float, float]],
        tmp_path: Path,
    ) -> None:
        self._fake_peaks(monkeypatch, [-1.0, -1.1, -1.6])
        normalize_loudness(tmp_path / "in", tmp_path / "out", TARGET)
        # 0.5 + 0.1, then 0.4 + 0.2 more.
        assert [t for _, t in encodes] == pytest.approx([0.0, 0.6, 1.2])

    def test_peak_exactly_at_ceiling_accepted(
        self,
        monkeypatch: pytest.MonkeyPatch,
        encodes: list[tuple[float, float]],
        tmp_path: Path,
    ) -> None:
        self._fake_peaks(monkeypatch, [-1.5])
        normalize_loudness(tmp_path / "in", tmp_path / "out", TARGET)
        assert len(encodes) == 1

    def test_gives_up_after_max_attempts(
        self,
        monkeypatch: pytest.MonkeyPatch,
        encodes: list[tuple[float, float]],
        tmp_path: Path,
        caplog: pytest.LogCaptureFixture,
    ) -> None:
        self._fake_peaks(monkeypatch, [-1.0, -1.1, -1.2, -1.3])
        with (
            caplog.at_level(logging.INFO, logger=audio.logger.name),
            pytest.raises(LoudnessError, match="true peak still above"),
        ):
            normalize_loudness(tmp_path / "in", tmp_path / "out", TARGET)
        assert len(encodes) == 4
        # The per-attempt peaks are visible at INFO.
        (record,) = [r for r in caplog.records if r.levelno == logging.INFO]
        assert "-1.00, -1.10, -1.20, -1.30" in record.getMessage()


# ---------------------------------------------------------------------------
# True peak
# ---------------------------------------------------------------------------


class TestMeasureTruePeak:
    def test_agrees_with_loudnorm(self, make_tone: MakeTone) -> None:
        for name, volume in (("a.wav", -18), ("b.mp3", -6), ("c.wav", 0)):
            tone = make_tone(name, volume, spike=volume == 0)
            assert measure_true_peak(tone) == pytest.approx(
                measure_loudness(tone).true_peak_dbtp, abs=0.05
            ), name

    def test_silence_is_minus_inf(self, make_tone: MakeTone) -> None:
        assert measure_true_peak(make_tone("s.wav", -1000)) == float("-inf")

    def test_undecodable_file_raises(self, tmp_path: Path) -> None:
        junk = tmp_path / "junk.mp3"
        junk.write_bytes(b"not audio at all" * 100)
        with pytest.raises(LoudnessError, match="ffmpeg exited"):
            measure_true_peak(junk)

    @pytest.mark.parametrize(
        ("stderr", "match"),
        [("no stats here", "no peak level"), ("Peak level dB: loud", "unreadable")],
    )
    def test_bad_output_raises(
        self, monkeypatch: pytest.MonkeyPatch, stderr: str, match: str
    ) -> None:
        monkeypatch.setattr(audio, "_run_ffmpeg", lambda args, cancel=None: stderr)
        with pytest.raises(LoudnessError, match=match):
            measure_true_peak(Path("x.mp3"))
